# site settings
title: Chiou Lab
subtitle: Patterning Principles in Microbiology
email: jchiou@gate.sinica.edu.tw
welcoming: Discover the patterns in life.
description: Now recruiting at all positions!
baseurl: https://jchioulab.github.io/ # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:  Jian-geng Chiou
street_address: R402, IPMB, Academia Sinica No. 128, Section 2, Academia Rd
city: Nangang District
state: Taipei City
zip_code: 115
country: Taiwan
phone: +886-2-27871113

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/JChiouLab
  Youtube: 
  Twitter: https://twitter.com/jiangengchiou
  Discord: https://
 

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 